name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Pacotes necessários para a nova arquitetura
  http: ^1.2.1
  table_calendar: ^3.1.2
  
  # Pacotes de ícones e outros
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # Dependência adicionada para gerar os ícones
  flutter_launcher_icons: ^0.13.1

# Configuração para o pacote de ícones
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

