name: Deploy Flutter Web

# Aciona a ação sempre que houver um push para o ramo 'main'
on:
  push:
    branches:
      - main

# Concede permissões de escrita à ação
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Obtém o código do seu repositório
      - uses: actions/checkout@v3

      # 2. Configura o ambiente Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 3. CORREÇÃO IMPORTANTE: Entra na pasta do projeto Flutter
      - name: Change to Flutter directory
        run: cd flutter_application_1

      # 4. Instala as dependências
      - name: Install dependencies
        run: flutter pub get
        working-directory: ./flutter_application_1 # Executa o comando na pasta correta

      # 5. Constrói a versão web
      - name: Build Web
        run: flutter build web --release --base-href /Projeto-Agenda-de-Shows/
        working-directory: ./flutter_application_1 # Executa o comando na pasta correta

      # 6. Faz o deploy dos ficheiros construídos para o ramo 'gh-pages'
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Aponta para a pasta de build correta
          publish_dir: ./flutter_application_1/build/web
        #2
